### ISSUE TITLE
CyTube 3.0 support

### ISSUE THREAD

**Issue by czaks** [zimny-lech/CyTube-Plus#1]
Are you planning to do the porting to CyTube 3.0? Because in a matter of days I want to update synchtu.be to CyTube 3.0 and I want to synchronize the effort with you.

If you have no CyTube 3.0 instance to test, I can provide you one.

**Comment by zimny-lech** [comment]
It was harder and took more time than I thought, but I already finished rewriting code for CyTube 3.0. I will test it soon on Synchtube.
